name: WallJump
version: 2.0.4
main: me.arthed.walljump.WallJump
api-version: 1.16
softdepend: [ WorldGuard ]
authors: [ Arthed ]
description: Adds an easy to understand, yet still challenging wall jump mechanic
